### ISSUE TITLE
F2 key not working correctly in chronogram

### ISSUE THREAD

**Issue by curiouspiano** [emrankb/logisim-evolution#6]
From forked repo:
  https://github.com/reds-heig/logisim-evolution/issues/15

The F2 key allows to do a clock step on the main clock. The problem is that it Logisim looks for the clock only in the circuit marked as main when handling the F2 key (file ChronoFrame.java), ignoring the circuit that is analysed with the chronogram at that precise moment if it is not marked as such.

The functioning of the F2 key should be revised, making it work properly and making its behaviour intuitive.

**Comment by curiouspiano** [comment]
"Chronogram" button opens the LogFrame.java (/src/main/java/com/cburch/logisim/gui/log) 
Added a fix to add a key listener which ticks the current simulator. Listener does not seem to persist on window alterations, however.

**Comment by curiouspiano** [comment]
Fixed in recent commit, F2 key now responds properly in the LogFrame window, most importantly the Table window.

**Comment by maehne** [comment]
Will you upstream this and also other fixes to [reds-heig/logisim-evolution](https://github.com/reds-heig/logisim-evolution) by making preferrably individual pull requests?

**Comment by curiouspiano** [comment]
@maehne I've opened a pull request to [reds-heig/logisim-evolution](https://github.com/reds-heig/logisim-evolution) /develop for this fix. We will get around to it for each as they're completed.
