### ISSUE TITLE
Auto-pan while wiring or placing components

### ISSUE THREAD

**Issue by emrankb** [emrankb/logisim-evolution#8]
https://github.com/reds-heig/logisim-evolution/issues/255
_____________________________________________________________________________________________________
Make Logisim to automatically pan into the direction of the mouse if the latter hits the screen border while one is wiring or placing components. Currently, one has to use the arrow keys for panning in this situation.

Auto-pan while wiring or placing components

**Comment by emrankb** [comment]
Modified the code so now it auto-pans to the direction of the mouse, while wiring or placing components.

**Comment by emrankb** [comment]
Test if it performs as expected in different situations.

**Comment by emrankb** [comment]
> Test if it performs as expected in different situations.

Final fix was made and auto-pan functions as expected.

**Comment by maehne** [comment]
@emrankb: It seems that you are interested into fixing bugs in Logisim-evolution. Would you and your colleagues be willing to contribute your improvements to [reds-heig/logisim-evolution](https://github.com/reds-heig/logisim-evolution)? We are very open for 3rd-party contributions and collaboration. Everyone can report issues, make pull requests and participate in the discussion/review of improvements.

**Comment by emrankb** [comment]
I fixed the issue. Do you want to merge with your main? @maehne

I am also working on another bug as of now :)

**Comment by maehne** [comment]
Thanks for working on some of Logisim-evolution's long-standing issues! Please, make any pull requests always against the [`develop` banch](https://github.com/reds-heig/logisim-evolution/tree/develop) of Logisim-evolution. It would be helpful, if you could briefly describe in the pull request, which issue # from our issue tracker you have fixed, how you did it, and how you tested the fix.

**Comment by emrankb** [comment]
I fixed it by adding a new rectangle and Making the newly created rectangle the new visible canvas. This was done in src/main/java/com/cburch/logisim/gui/main/Canvas.java in the function named dragged. Here is the code I added:
————————
Rectangle r = new Rectangle(e.getX(), e.getY(), 1, 1);
scrollRectToVisible(r);
————————-

How I tested that it works is by dragging a wire outside of the visible canvas and it did automatically moved the scroller so that the wiring can continue. Which it didn’t before. Before this fix you had to manually move the scroller which could be more work since you have to interrupt the drag.

**Comment by emrankb** [comment]
When I tested it, I saw that it is working correctly by a zoom-level of 100%. Changing the zoom level to something else than 100% will result in a "strange behavior" in the sense that it will pan to the left (with jumps), but not to the right. I am guessing that the mouse coordinates (e.getX() and e.getY()) need to be scaled with the zoom-factor.

**Comment by emrankb** [comment]
I fixed it now so that the auto-pan feature works for all the zoom levels.
